### ISSUE TITLE
Only some Application ELB Metrics collected

### ISSUE THREAD

**Issue by JohannesRu** [ivx/yet-another-cloudwatch-exporter#49]
Hey, 

We've been using the tool to get our classic ELB CloudWatch metrics into Prometheus. Works great thanks a lot!! 👏
As our architecture evolves we now have application ELBs as well whose metrics we want to track. 

1. In order to collect those I noticed an additional IAM permission had to be granted (could adjust that in the Readme via PR if this is intended, just let me know)
![image](https://user-images.githubusercontent.com/3695123/53838497-8a087d80-3f95-11e9-9bb4-58d386071237.png)

2. Unfortunately this still did not quite fix it for us. Only a few of the desired metrics are exported. 
![image](https://user-images.githubusercontent.com/3695123/53838588-c20fc080-3f95-11e9-9d3a-482a17c98dca.png)
In the AWS CloudWatch dashboard I do see values for all the metrics configured. I added the configmap below. Is there anything we do wrong?

Best regards and keep up the good work!
Johannes

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-exporter-config
data:
  config.yml: |-
    discovery:
      exportedTagsOnMetrics:
        elb:
        - kubernetes.io/service-name
        - kubernetes.io/cluster/my-cluster
        alb:
        - kubernetes.io/service-name
        - kubernetes.io/cluster/my-cluster
      jobs:
      - type: "elb" 
        region: eu-west-1
        searchTags:
          - Key: kubernetes.io/cluster/my-cluster
            Value: owned
        metrics:
          - name: RequestCount
            statistics:
            - 'Sum'
            period: 60
            length: 300
          - name: BackendConnectionErrors
            statistics:
            - 'Sum'
            period: 60
            length: 300
      - type: "alb" 
        region: eu-west-1
        searchTags:
          - Key: kubernetes.io/cluster/my-cluster
            Value: owned
        metrics:
          - name: ActiveConnectionCount
            statistics:
            - 'Sum'
            period: 60
            length: 600
          - name: HTTPCode_ELB_5XX_Count
            statistics:
            - 'Sum'
            period: 60
            length: 300
          - name: HTTPCode_ELB_4XX_Count
            statistics:
            - 'Sum'
            period: 60
            length: 300
          - name: HTTPCode_ELB_3XX_Count
            statistics:
            - 'Sum'
            period: 60
            length: 300
          - name: RejectedConnectionCount
            statistics:
            - 'Sum'
            period: 60
            length: 300
          - name: TargetResponseTime
            statistics:
            - 'Sum'
            period: 60
            length: 300
          - name: RequestCount
            statistics:
            - 'Sum'
            period: 60
            length: 300
          - name: ClientTLSNegotiationErrorCount
            statistics:
            - 'Sum'
            period: 60
            length: 300
```

**Comment by tsupertramp** [comment]
Thanks for the nice description of your problem and the thank you words. That made me happy!

We are not using albs internally so its always difficult for me to debug the real use cases for that.

I will merge this in the next days and during that will debug your issue as well.
https://github.com/ivx/yet-another-cloudwatch-exporter/issues/42

Greetings, Thomas

**Comment by tsupertramp** [comment]
Fix released in 0.13.0-alpha - Could you verify it works on your side? @JohannesRu

**Comment by JohannesRu** [comment]
Hey,
thanks for the quick response. Using `0.13.0-alpha` now and we have some progress... 
The metrics are still not visible to me but in the logs of the `0.13.0-alpha`-container the following error shows up:

```
2019/03/19 08:33:59 Parse config..
2019/03/19 08:33:59 Startup completed
2019/03/19 08:35:00 http: panic serving 172.20.5.198:60894: descriptors reported by collector have inconsistent label names or help strings for th
e same fully-qualified name, offender is Desc{fqName: "aws_alb_target_response_time_sum", help: "Help is not implemented yet.", constLabels: {dime
nsion_LoadBalancer="app/24c9864e-ruum-canvascaalb-8a57/b4517c1d4ff1f9b2",dimension_TargetGroup="targetgroup/24c9864e-275222effbd60316035/75ac09540
20acee4",name="arn:aws:elasticloadbalancing:eu-west-1:687453745425:targetgroup/24c9864e-275222effbd60316035/75ac0954020acee4",tag_kubernetes_io_cl
uster_eks_dev="owned",tag_kubernetes_io_service_name="canvas-ca-load-balancer"}, variableLabels: []}
goroutine 33 [running]:
net/http.(*conn).serve.func1(0xc420208140)
        /usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x8f4d40, 0xc421e560e0)
        /usr/local/go/src/runtime/panic.go:502 +0x229
yace/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc4220def50, 0xc420ca7cd0, 0x1, 0x1)
        /go/src/yace/vendor/github.com/prometheus/client_golang/prometheus/registry.go:391 +0x9e
main.metricsHandler(0xa340e0, 0xc420254000, 0xc42024c000)
        /go/src/yace/main.go:50 +0x2e2
net/http.HandlerFunc.ServeHTTP(0x9b3580, 0xa340e0, 0xc420254000, 0xc42024c000)
        /usr/local/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xcaec60, 0xa340e0, 0xc420254000, 0xc42024c000)
        /usr/local/go/src/net/http/server.go:2340 +0x130
net/http.serverHandler.ServeHTTP(0xc4201e6750, 0xa340e0, 0xc420254000, 0xc42024c000)
        /usr/local/go/src/net/http/server.go:2697 +0xbc
net/http.(*conn).serve(0xc420208140, 0xa35ae0, 0xc42006a080)
        /usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2798 +0x27b
```

Hope this helps. If I can support you with any additional logs/info. Let me know.

**Comment by tsupertramp** [comment]
Could it be that you have two discovery jobs which both find the same albs? @JohannesRu

**Comment by JohannesRu** [comment]
Sorry for the late response, I had a another look. 

I am still using the config as posted in initial comment, however I removed ALB metric TargetResponseTime which triggered the `panic serving 172.20.5.198:60894: descriptors reported by collector have inconsistent label names` error. 

Now, I finally see the other ALB metrics such as ActiveConnectionCount and HTTPCode_ELB_5XX_Count which is already of big help!

**Comment by tsupertramp** [comment]
I will spin up an ALB on Friday and test the behaviour. Maybe i find something out. Thanks for the tip regarding the metrics.

We do not have one in our infrastructure as we only use tcp elbs for everything.

**Comment by tsupertramp** [comment]
This should be fixed now.
